### ISSUE TITLE
It doesn't listen directories with just one item

### ISSUE THREAD

**Issue by robjuz** [kapersoft/flysystem-sharefile#3]
Hi.
I appreciate your work. Wanted to use it in my laravel project and found a Problem.

If in a directory is just one entry, an empty array is returned.

in the `buildItemList` function there is this check

```
if ($children['FileCount'] < 2 || ! isset($children['Children'])) {
    return [];
}
```

the `$children['FileCount'] < 2` part should probably we omitted

**Comment by kapersoft** [comment]
Hi,

Thanks for using this package :smile:

The ShareFile API has some issues when using it together with ShareFile WebDav (see [my issues](https://community.sharefilesupport.com/citrixsharefile/people/kapersoft?profile-topic-list[settings][type]=problem) on SF-forum). That's why this bug was introduced to the code.

I have changed the check in `buildItemList` to 
```
if (! isset($children['Children']) || count($children['Children']) < 1) {
    return [];
}
```
and pushed it to the master.

Can you check if this solutions work for you?

**Comment by robjuz** [comment]
It's working like a charm :smile:
